### ISSUE TITLE
Indice de confiance beaucoup plus bas sur Lyon

### ISSUE THREAD

**Issue by nuxper** [cquest/retrosirene#2]
Les adresses des établissements du fichier SIRENE ont une distribution des niveaux de confiance beaucoup plus bas à Lyon.
J'ai sorti la distribution des niveau de confiance dans le Rhone entre Lyon intramuros et le reste du département.
![stats_confidence_level_rhone](https://user-images.githubusercontent.com/7891262/81337280-112a1780-90ab-11ea-8dab-eab526656f72.png)
Pourtant de ce que j'ai pu voir sur plusieurs dizaines d'adresses, elles sont largement bonnes.
J'imagine que cela vient du géocodeur mais je préfère créer le bug ici pour l'instant car je ne suis pas expert ;)
Cela bloque l'intégration de SIRENE dans osmose sur Lyon qui ne propose que l'intégration des établissements avec un niveau de confiance > 0.9

**Comment by nuxper** [comment]
Salut @cquest
Tu saurais me pointer dans la bonne direction ? Je veux bien essayer un fix mais je ne sais pas où regarder ?
Le problème semble toujours existant

**Comment by cquest** [comment]
Problème lié aux arrondissements, même chose sur Marseille et corrigé pour la prochaine livraison mensuelle qui ne saurait tarder !
