### ISSUE TITLE
Définition des colonnes du CSV geo-sirene des établissements actifs

### ISSUE THREAD

**Issue by glenfant** [cquest/retrosirene#4]
Bonjour, et un grand merci pour les données que vous fournissez.

Ceci est juste une question (et suggestion) : Où puis-je trouver la spécification des différentes colonnes de la table CSV du fichier etablissements_actifs que vous publiez ici : https://data.cquest.org/geo_sirene/2020-07/

J'avoue être un peu perdu dans les documents de l'INSEE, et ne suis pas arrivé à trouver la bonne ressource. Je vous suggère en passant de laisser le lien vers ce document dans le https://data.cquest.org/geo_sirene/2020-07/LISEZMOI.txt et ses successeurs, pour éviter d'être dérangé par des questions de noob comme celle que vous êtes en train de lire ;).

Cordialement et merci par avance pour votre réponse.

**Comment by cquest** [comment]
Ces fichiers sont à un ancien format que ne diffuse plus l'INSEE et à considérer comme obsolètes. retrosirene ne fait que les regénérer pour une retro-compatibilité pour les personnes qui n'ont pas encore fait évoluer leur SI.

Il est préférable d'utiliser les fichiers au format "v2019" qui eux sont documentés par l'INSEE.
